spring:
 redis:
    database: 0
    host: 10.16.8.94
    password:
    port: 6379
    pool:
    max-active: 8
    max-wait: -1
    max-idle: 8
    min-idle: 0
    timeout: 0
 cache:
    type: REDIS
    cache-names: redisCache